### ISSUE TITLE
Submission for JOSS

### ISSUE THREAD

**Issue by bmorris3** [bmorris3/aesop#14]
Hey @tzdwi, 

I'm working on two papers right now that could both cite `aesop`, so why not get that review process started so we can cite it? 

I'm starting to draft the JOSS "paper" in the [wiki page](https://github.com/bmorris3/aesop/wiki), which I'm pretty sure you can edit too. Would you give it a look over and consider adding/editing? We can have discussion here in the issue.

**Comment by tzdwi** [comment]
Sure thing!!

Trevor

**Comment by bmorris3** [comment]
@tzdwi lemme know if/when you're settled with your input, and I'll submit!

**Comment by tzdwi** [comment]
Looks good to me! Only comment: might be worth emphasizing that the flux-calibration/continuum normalization/some other stuff (if im remembering correctly) is non-standard, but we offer robust validated standard-issue stuff too. But this is also my first JOSS rodeo 🤷‍♂️

**Comment by bmorris3** [comment]
Ok, I'll make the draft and submit!
