### ISSUE TITLE
Review - License doesn't match

### ISSUE THREAD

**Issue by wtgee** [bmorris3/aesop#16]
License on repo is MIT, review paper for JOSS has CC-YA (probably the template default?)

**Comment by bmorris3** [comment]
I'm a bit stumped by this one. Hey @jakevdp/@arfon – should the JOSS submission license match the software license?

**Comment by arfon** [comment]
JOSS _papers_ are CC-BY, the license choice of the software (MIT in this case) is picked by the author and respected.

**Comment by bmorris3** [comment]
Thanks for the clarification @arfon!
