### ISSUE TITLE
Review - plots inconsistently include axis labels

### ISSUE THREAD

**Issue by wtgee** [bmorris3/aesop#22]
Potentially confusing. Titles are missing on all plots but might not be as important.

![screenshot_2018-07-27 example 2](https://user-images.githubusercontent.com/70736/43294339-241ad214-9182-11e8-90c2-1d7b10b20810.png)

![screenshot_2018-07-27 example 3](https://user-images.githubusercontent.com/70736/43294338-23ce2cfc-9182-11e8-976b-332955c099bf.png)

**Comment by wtgee** [comment]
Seems to just be missing on figures with subplots but should probably still be included either on each subplot or a shared.

**Comment by bmorris3** [comment]
(for openjournals/joss-reviews#854)
