### ISSUE TITLE
Extract 2D Spectrum from Echelle

### ISSUE THREAD

**Issue by exowanderer** [bmorris3/aesop#27]
This code seems to do very well at visualizing and gaining information from 1D spectrum from Echelle spectrographs, after the 2D Echelle spectra have been extracted into a stack of 1D spectra.

How do we take the 2D Echelle spectra (photons vs pixels) with the geometric distortions and needed wavelength calibrations (from comparison spectra) to generate these 1D spectra here.

Is there are section of this package that extracts the 1D spectra from a 2D image?  

{silently screaming: 
please don't say IRAF...
please don't say IRAF... 
please don't say IRAF...
please don't say IRAF...}

**Comment by bmorris3** [comment]
@exowanderer Unfortunately we've relegated the 2D->1D task to IRAF until a suitable replacement is developed in the astropy community. We've taken this approach for two reasons: 
1) Continuity with legacy reductions: a single `ReduceARCES.cl` IRAF script has been doing ARCES reductions for decades, so for reproducibility's sake, it makes sense to keep using it
2) It would be reinventing the wheel to rewrite it in Python, as there's no good Python alternative yet to `apextract`, in particular. 

Our philosophy with `aesop` is to pick up where IRAF leaves off.

**Comment by exowanderer** [comment]
Thank you for the updated information. I appreciate knowing this; although I refused to use IRAF for reasons related to time and {wanting to avoid having} heart conditions.
